DEFAULTS = {
    "provider": {
        "default": "lm_studio",
        "lm_studio": {"base_url": "http://localhost:1234/v1", "timeout": 300, "max_retries": 3},
        "ollama": {"base_url": "http://localhost:11434/v1", "timeout": 300, "max_retries": 3},
        "vllm": {"base_url": "http://localhost:8000/v1", "timeout": 300, "max_retries": 3},
        "openai": {"base_url": "https://api.openai.com/v1", "timeout": 60, "max_retries": 3},
        "openrouter": {"base_url": "https://openrouter.ai/api/v1", "timeout": 60, "max_retries": 3},
        "anthropic": {"base_url": "https://api.anthropic.com/v1", "timeout": 120, "max_retries": 3},
        "gemini": {"base_url": "https://generativelanguage.googleapis.com/v1beta", "timeout": 60, "max_retries": 3},
        "mistral": {"base_url": "https://api.mistral.ai/v1", "timeout": 60, "max_retries": 3},
        "deepseek": {"base_url": "https://api.deepseek.com/v1", "timeout": 60, "max_retries": 3},
    },
    "model": {
        "default": "local-model",
        "temperature": 0.7,
        "max_tokens": 4096,
        "top_p": 0.95,
        "stop_sequences": [],
    },
    "cli": {
        "theme": "auto",
        "syntax_theme": "monokai",
        "multi_line": True,
        "history_size": 1000,
        "show_status_bar": True,
        "show_token_count": False,
        "auto_suggest": True,
    },
    "memory": {
        "max_context_tokens": 32000,
        "compaction_threshold": 0.8,
        "session_persistence": True,
        "max_sessions": 50,
    },
    "security": {
        "ask_before_tool": False,
        "allowed_commands": [],
        "blocked_commands": ["rm -rf /", "sudo rm -rf /", "del /f /s /q"],
        "sandbox_enabled": False,
    },
    "logging": {
        "level": "INFO",
        "json_format": False,
        "verbose": False,
        "rotation": "10 MB",
        "retention": 5,
    },
    "cache": {
        "enabled": True,
        "default_ttl_provider": 300,
        "default_ttl_workspace": 60,
    },
    "workspace": {
        "auto_detect": True,
        "index_depth": 3,
        "ignored_dirs": [
            ".git",
            "__pycache__",
            "node_modules",
            ".venv",
            "venv",
            ".tox",
            ".egg-info",
            "dist",
            "build",
            ".idea",
            ".vscode",
        ],
    },
    "plugins": {
        "enabled": True,
        "safe_mode": True,
        "plugin_dirs": ["~/.config/bytecli/plugins", ".bytecli/plugins"],
        "enabled_plugins": ["*"],
        "auto_load": True,
    },
    "skills": {
        "enabled": True,
        "skill_dirs": ["~/.config/bytecli/skills", ".bytecli/skills"],
        "auto_load": True,
        "max_instructions_length": 20000,
        "priority_threshold": 0,
    },
}
